services:
  headscale:
    image: docker.io/headscale/headscale:latest
    restart: unless-stopped
    container_name: headscale
    ports:
      - "8080:8080"
    command: serve
    volumes:
      - ./:/etc/headscale:ro
      - ./headscale:/var/lib/headscale
